@echo off
setlocal
cd /d %~dp0
echo Iniciando Servidor ReviverPet...
echo Verificando dependencias...
python -m pip install -r requirements.txt --quiet
echo Iniciando API...
start /B python -m uvicorn backend.main:app --host 127.0.0.1 --port 8000
echo Aguardando o servidor iniciar...
timeout /T 4 /NOBREAK > nul
echo Abrindo o sistema em Modo Aplicativo...
start chrome.exe --app=http://127.0.0.1:8000
if %ERRORLEVEL% NEQ 0 (
    echo Erro ao abrir o Chrome. Tentando navegação normal...
    start http://127.0.0.1:8000
)
exit
